In [1]:
import pandas as pd

### Loading Dataset

In [5]:
df = pd.read_csv("/home/prajwalmac/Interview/ipl_matches.csv")
df

        id    Season  ...         umpire2                  umpire3
0        1  IPL-2017  ...        NJ Llong                      NaN
1        2  IPL-2017  ...          S Ravi                      NaN
2        3  IPL-2017  ...       CK Nandan                      NaN
3        4  IPL-2017  ...   C Shamshuddin                      NaN
4        5  IPL-2017  ...             NaN                      NaN
..     ...       ...  ...             ...                      ...
751  11347  IPL-2019  ...        O Nandan                   S Ravi
752  11412  IPL-2019  ...     Nitin Menon                Ian Gould
753  11413  IPL-2019  ...             NaN                      NaN
754  11414  IPL-2019  ...  Bruce Oxenford  Chettithody Shamshuddin
755  11415  IPL-2019  ...       Ian Gould              Nigel Llong

[756 rows x 18 columns]

In [6]:
df.head()

   id    Season       city  ...         umpire1        umpire2 umpire3
0   1  IPL-2017  Hyderabad  ...     AY Dandekar       NJ Llong     NaN
1   2  IPL-2017       Pune  ...  A Nand Kishore         S Ravi     NaN
2   3  IPL-2017     Rajkot  ...     Nitin Menon      CK Nandan     NaN
3   4  IPL-2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
4   5  IPL-2017  Bangalore  ...             NaN            NaN     NaN

[5 rows x 18 columns]

In [7]:
df.tail()

        id    Season  ...         umpire2                  umpire3
751  11347  IPL-2019  ...        O Nandan                   S Ravi
752  11412  IPL-2019  ...     Nitin Menon                Ian Gould
753  11413  IPL-2019  ...             NaN                      NaN
754  11414  IPL-2019  ...  Bruce Oxenford  Chettithody Shamshuddin
755  11415  IPL-2019  ...       Ian Gould              Nigel Llong

[5 rows x 18 columns]

In [8]:
df.shape

(756, 18)

In [9]:
df.isna()

        id  Season   city   date  ...  venue  umpire1  umpire2  umpire3
0    False   False  False  False  ...  False    False    False     True
1    False   False  False  False  ...  False    False    False     True
2    False   False  False  False  ...  False    False    False     True
3    False   False  False  False  ...  False    False    False     True
4    False   False  False  False  ...  False     True     True     True
..     ...     ...    ...    ...  ...    ...      ...      ...      ...
751  False   False  False  False  ...  False    False    False    False
752  False   False  False  False  ...  False    False    False    False
753  False   False  False  False  ...  False     True     True     True
754  False   False  False  False  ...  False    False    False    False
755  False   False  False  False  ...  False    False    False    False

[756 rows x 18 columns]

In [10]:
df.isnull().sum()

id                   0
Season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [11]:
df.head()

   id    Season       city  ...         umpire1        umpire2 umpire3
0   1  IPL-2017  Hyderabad  ...     AY Dandekar       NJ Llong     NaN
1   2  IPL-2017       Pune  ...  A Nand Kishore         S Ravi     NaN
2   3  IPL-2017     Rajkot  ...     Nitin Menon      CK Nandan     NaN
3   4  IPL-2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
4   5  IPL-2017  Bangalore  ...             NaN            NaN     NaN

[5 rows x 18 columns]

### Handling Missing Values

In [12]:
df_clean = df.copy()

# Strategy 1: Drop rows where 'winner' is missing (only 4 rows - likely tied/no result)
print(f"\nRows before dropping missing 'winner': {len(df_clean)}")
df_clean = df_clean.dropna(subset=['winner'])
print(f"Rows after dropping missing 'winner': {len(df_clean)}")

Rows before dropping missing 'winner': 756
Rows after dropping missing 'winner': 752

In [13]:
# strategy 2: filling 'city' with mode (most frequent city)
most_frequent_city = df_clean['city'].mode()[0]
df_clean['city'].fillna(most_frequent_city, inplace=True)
print(f"\n'city' missing values filled with mode: '{most_frequent_city}'")

'city' missing values filled with mode: 'Mumbai'

/tmp/ipykernel_31509/759935577.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['city'].fillna(most_frequent_city, inplace=True)

In [14]:

#strategy 3: filling 'player_of_match' with placeholder
df_clean['player_of_match'].fillna('Unknown', inplace=True)
print("'player_of_match' missing values filled with 'Unknown'")

'player_of_match' missing values filled with 'Unknown'

/tmp/ipykernel_31509/2203968110.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['player_of_match'].fillna('Unknown', inplace=True)

In [15]:

# strategy 4: filling umpire columns with unknown
df_clean['umpire1'].fillna('Unknown', inplace=True)
df_clean['umpire2'].fillna('Unknown', inplace=True)

/tmp/ipykernel_31509/694934905.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['umpire1'].fillna('Unknown', inplace=True)
/tmp/ipykernel_31509/694934905.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['umpire2'].fillna('Unknown', inplace=True)

In [16]:
# strategy 5: Dropping 'umpire3' because it is  missing 637 rows in the dataset 
df_clean.drop(columns=['umpire3'], inplace=True)
print("umpire3 column dropped")

print("\nMissing values after treatment ")
print(df_clean.isnull().sum())

umpire3 column dropped

Missing values after treatment
id                 0
Season             0
city               0
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
result             0
dl_applied         0
winner             0
win_by_runs        0
win_by_wickets     0
player_of_match    0
venue              0
umpire1            0
umpire2            0
dtype: int64

### Removing Duplicate rows

In [17]:
print(f"\nTotal duplicate rows: {df_clean.duplicated().sum()}")
df_clean = df_clean.drop_duplicates()

# No any duplicate rows so doesnt need to remove anything
print(f"Dataset shape after removing duplicates: {df_clean.shape}")

Total duplicate rows: 0
Dataset shape after removing duplicates: (752, 17)

### LAbel Encoding

In [18]:

from sklearn.preprocessing import LabelEncoder
import pandas as pd

df_encoded = df_clean.copy()

# label encoder object
le = LabelEncoder()

df_encoded['toss_decision_enc'] = le.fit_transform(df_encoded['toss_decision'])

print("toss_decision encoding:")
print("bat   →", 0)
print("field →", 1)
print(df_encoded[['toss_decision', 'toss_decision_enc']].head())

toss_decision encoding:
bat   → 0
field → 1
  toss_decision  toss_decision_enc
0         field                  1
1         field                  1
2         field                  1
3         field                  1
4           bat                  0

### One Hot Encoding

In [ ]:
# One-Hot Encoding for categorical columns
ohe_cols = ['Season', 'city']  # columns with nominal data
df_encoded = pd.get_dummies(df_encoded, columns=ohe_cols, drop_first=True)

print(f"Shape after OHE: {df_encoded.shape}")
print("Sample new OHE columns:")
ohe_sample = [c for c in df_encoded.columns if c.startswith('city_') or c.startswith('season_')]
print(ohe_sample[:10])

Shape after OHE: (752, 59)

Sample new OHE columns:
['city_Ahmedabad', 'city_Bangalore', 'city_Bengaluru', 'city_Bloemfontein', 'city_Cape Town', 'city_Centurion', 'city_Chandigarh', 'city_Chennai', 'city_Cuttack', 'city_Delhi']

In [22]:
df_clean.to_csv('ipl_clean.csv', index=False)
print("preprocessed dataset saved")

preprocessed dataset saved